name: Feature Request
description: Suggest a new feature or enhancement for TIP
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your input helps make TIP better for everyone.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Must Have - Can't use the app without it"
        - "Should Have - Would significantly improve experience"
        - "Nice to Have - Would be a useful addition"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area would this feature improve?
      options:
        - "Trip Planning"
        - "Report Generation"
        - "Visa Information"
        - "Weather & Climate"
        - "Attractions & Activities"
        - "User Profile"
        - "Sharing & Collaboration"
        - "Mobile Experience"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem or need does this feature address?
      placeholder: "As a user, I want to... so that I can..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: mockup
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other apps.
      placeholder: Drag and drop images here or paste URLs...

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: What type of traveler are you?
      options:
        - "Frequent Business Traveler"
        - "Occasional Leisure Traveler"
        - "Adventure/Backpacker"
        - "Family Traveler"
        - "Digital Nomad"
        - "Other"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, research, or references about the feature request here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be interested in helping implement this feature
        - label: I can provide additional user testing/feedback

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
